'use client';

import { FormEvent, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';

export function ContactForm({ compact = false, appointment = false }: { compact?: boolean; appointment?: boolean }) {
  const [sent, setSent] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setError(''); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()); if (appointment) { payload.preferred_date = payload.date || ''; payload.preferred_time = payload.time || ''; delete payload.date; delete payload.time; payload.appointment_type = payload.service || ''; delete payload.service; } else { payload.subject = payload.service || ''; delete payload.service; } try { const response = await fetch(appointment ? '/api/appointments' : '/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || 'Please check the form and try again.'); setSent(true); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : 'We could not send your message. Please try again.'); } finally { setSubmitting(false); } }
  return <form className={`contact-form ${compact ? 'contact-form-compact' : ''}`} onSubmit={submit}>{sent ? <div className="form-success"><strong>Thank you for reaching out.</strong><p>Your message has been received by the AfroVive team. We&apos;ll be in touch soon.</p><button type="button" className="text-link" onClick={() => setSent(false)}>Send another message</button></div> : <><div className="form-row"><label>Full name<input name="name" placeholder="Your name" required /></label><label>Email address<input name="email" type="email" placeholder="you@example.com" required /></label></div><div className="form-row"><label>Phone number<input name="phone" type="tel" placeholder="+256 ..." /></label><label>{appointment ? 'Preferred focus area' : 'What can we help with?'}<select name="service" defaultValue=""><option value="" disabled>Select an option</option><option>Partnerships</option><option>Programs and research</option><option>Internship</option><option>Media and speaking</option><option>General enquiry</option></select></label></div>{appointment && <div className="form-row"><label>Preferred date<input name="date" type="date" /></label><label>Preferred time<input name="time" type="time" /></label></div>}<label>Message<textarea name="message" placeholder="Tell us a little more..." rows={compact ? 4 : 6} required /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-green" type="submit" disabled={submitting}>{submitting ? 'Sending…' : 'Send message'} {!submitting && <ArrowUpRight size={17} />}</button><p className="form-note">Your message is securely stored for the AfroVive team.</p></>}</form>;
}
