'use client';

import { ArrowUpRight, ChevronDown, Menu, X } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';
import type { NavigationItem, Post, Program } from '@/lib/types';

export function SiteHeaderNav({ items, programs, posts }: { items: NavigationItem[]; programs: Program[]; posts: Post[] }) {
  const [open, setOpen] = useState(false);
  const [expanded, setExpanded] = useState<string | null>(null);
  const close = () => { setOpen(false); setExpanded(null); };
  return <><button className="menu-toggle" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><nav className={open ? 'main-nav is-open' : 'main-nav'} aria-label="Main navigation"><ul>{items.map((item) => { const isPrograms = item.label.toLowerCase().includes('program'); const isInsights = item.label.toLowerCase().includes('insight'); const hasMega = isPrograms || isInsights; return <li key={item.url} className={`${item.children?.length || hasMega ? 'has-children' : ''} ${hasMega ? 'nav-mega' : ''} ${expanded === item.url ? 'is-expanded' : ''}`}><div className="nav-link-row"><Link href={item.url} target={item.external ? '_blank' : undefined} rel={item.external ? 'noreferrer' : undefined} onClick={close}>{item.label}</Link>{(item.children?.length || hasMega) ? <button className="mega-toggle" aria-label={`Toggle ${item.label} menu`} aria-expanded={expanded === item.url} onClick={() => setExpanded(expanded === item.url ? null : item.url)}><ChevronDown size={14} /></button> : null}</div>{hasMega ? <div className="mega-panel">{isPrograms ? <><div className="mega-intro"><p className="eyebrow">Programmes</p><h3>Work built with communities.</h3><Link href={item.url} className="text-link" onClick={close}>View all programmes <ArrowUpRight size={14} /></Link></div><div className="mega-items">{programs.map((program) => <Link href={`/programs/${program.slug}`} key={program.slug} onClick={close}><span>{program.short_title || program.title}</span><small>{program.short_description}</small></Link>)}</div></> : <><div className="mega-intro"><p className="eyebrow">Insights</p><h3>Learning worth sharing.</h3><Link href={item.url} className="text-link" onClick={close}>View all insights <ArrowUpRight size={14} /></Link></div><div className="mega-items">{posts.map((post) => <Link href={`/blog/${post.slug}`} key={post.slug} onClick={close}><span>{post.title}</span><small>{post.excerpt}</small></Link>)}</div></>}</div> : item.children?.length ? <ul className="submenu">{item.children.map(child => <li key={child.url}><Link href={child.url} target={child.external ? '_blank' : undefined} rel={child.external ? 'noreferrer' : undefined} onClick={close}>{child.label}</Link></li>)}</ul> : null}</li>; })}</ul><Link href="/support-us" className="header-cta" onClick={close}>Support us</Link></nav></>;
}
