export type Program = { slug: string; title: string; shortTitle: string; summary: string; image: string; imageAlt: string; body: string; points: string[] };
export type Project = { slug: string; title: string; category: string; summary: string; image: string; imageAlt: string };
export type Faq = { question: string; answer: string };

export const programs: Program[] = [
  { slug: 'health-well-being', title: 'Health & Well-being', shortTitle: 'Health & well-being', summary: 'Expanding access to youth-friendly health services, mental health support and HIV prevention.', image: '/images/afrovive/programs/health-well-being.jpeg', imageAlt: 'Young people in a community health discussion', body: 'We work with communities and partners to make health information and services more accessible, youth-friendly and responsive to the realities young people face.', points: ['Youth-friendly health and wellbeing services', 'Mental health and psychosocial support', 'HIV prevention and cure research advocacy'] },
  { slug: 'skill-development', title: 'Skill Development', shortTitle: 'Skill development', summary: 'Promoting training, digital literacy and life skills so young people can thrive.', image: '/images/afrovive/programs/skill-development.jpg', imageAlt: 'Learners collaborating during a skills workshop', body: 'AfroVive creates pathways from learning to opportunity through practical training, digital literacy and leadership development for young people.', points: ['Digital literacy and employability', 'Leadership and life skills', 'Inclusive access to opportunity'] },
  { slug: 'srh-advocacy', title: 'SRH Advocacy', shortTitle: 'SRH advocacy', summary: 'Advancing sexual and reproductive health rights through community-based advocacy.', image: '/images/afrovive/programs/empowering-youth.jpeg', imageAlt: 'Young people working together in a learning space', body: 'Through partnerships with communities, institutions and young advocates, we work to eliminate harmful practices and strengthen sexual and reproductive health and rights.', points: ['Sexual and reproductive health rights', 'Community-led advocacy', 'Ending harmful practices'] },
  { slug: 'climate-justice', title: 'Climate Justice', shortTitle: 'Climate justice', summary: 'Integrating environmental sustainability and climate resilience into health interventions.', image: '/images/afrovive/hero/hero4.webp', imageAlt: 'Young Africans represented in a bold illustration', body: 'We connect climate action with health equity so communities can build resilient systems and young people can lead the response to environmental change.', points: ['Climate-resilient health systems', 'Youth climate leadership', 'Community innovation'] },
  { slug: 'global-learning-exchange', title: 'Global Learning & Exchange', shortTitle: 'Global learning & exchange', summary: 'Hands-on public health and innovation programs connecting youth globally.', image: '/images/afrovive/projects/global-learning.jpeg', imageAlt: 'A public health learning session', body: 'Our exchange work brings learners, mentors and institutions together across borders to share knowledge and build practical public health leadership.', points: ['Public health placements', 'Cross-cultural learning', 'Mentorship and exchange'] }
];

export const projects: Project[] = [
  { slug: 'knowledge-without-borders', title: 'Knowledge Without Borders for Healthier Futures', category: 'Learning & exchange', summary: 'Sharing knowledge across borders and empowering Ugandan youth with practical health skills.', image: '/images/afrovive/projects/knowledge-without-borders.jpeg', imageAlt: 'A facilitator speaking to young people in a lecture hall' },
  { slug: 'inclusive-health-research', title: 'Empowering Youth to Lead Inclusive Health Research', category: 'Research & evidence', summary: 'Building inclusive health research from the ground up through global exchange.', image: '/images/afrovive/projects/about.webp', imageAlt: 'Young people collaborating in a workshop' },
  { slug: 'public-health-leaders', title: 'Shaping Global Public Health Leaders', category: 'Mentorship', summary: 'Mentorship and exchange that builds insight, skills and perspective for public health leadership.', image: '/images/afrovive/projects/global-learning.jpeg', imageAlt: 'A team in a collaborative meeting' }
];

export const faqs: Faq[] = [
  { question: 'What does AfroVive Health Foundation do?', answer: 'We advance health equity, youth empowerment, innovation and climate justice through community-driven programs, advocacy, research and learning exchanges.' },
  { question: 'Where does AfroVive work?', answer: 'We are headquartered in Kampala, Uganda, with an active and growing presence across East, West and Southern Africa through partnerships.' },
  { question: 'How can my organization partner with AfroVive?', answer: 'Send us a note through the contact page with a little information about your organization and the opportunity. Our team will follow up.' },
  { question: 'Can students apply for an internship?', answer: 'Yes. Our internship program connects students and early-career professionals to practical public health, research and community learning opportunities.' },
  { question: 'How can I support AfroVive?', answer: 'You can support our work by partnering with us, contributing resources, sharing our work or joining our youth-led programs.' }
];

export const team = [{ name: 'Dr Ben Kibirige', role: 'Founder & Executive Director', image: '/images/afrovive/team/dr-ben-director.webp', bio: 'A public health advocate committed to youth-led, community-owned solutions.' }, { name: 'Wamala Macci', role: 'Project Developer', image: '/images/afrovive/projects/about.webp', bio: 'Supporting the design and delivery of practical learning and innovation projects.' }];
